/* L'Oréal Product Database */
const PRODUCTS = [
  // ── SKINCARE ─────────────────────────────────────────────────
  {
    id: "revitalift-day-cream",
    name: "Revitalift Anti-Wrinkle + Firming Day Cream SPF 25",
    brand: "L'Oréal Paris",
    category: "Skincare",
    emoji: "",
    image: "img/anti-wrinke and firmiinf face .jpg",
    tagline: "Visibly reduces wrinkles in 4 weeks",
    description:
      "Formulated with Pro-Retinol and Centella Asiatica, this multi-action moisturizer visibly reduces wrinkles, firms skin, and protects with SPF 25. Dermatologist-tested and non-comedogenic. Apply every morning as the final step in your skincare routine before makeup.",
    keyIngredients: ["Pro-Retinol", "Centella Asiatica", "SPF 25"],
    skinType: "All skin types",
  },
  {
    id: "revitalift-hyaluronic-serum",
    name: "Revitalift 1.5% Pure Hyaluronic Acid Serum",
    brand: "L'Oréal Paris",
    category: "Skincare",
    emoji: "",
    image: "img/hyaluronic acid face serum.webp",
    tagline: "Triple-action hydration, plumped skin",
    description:
      "This concentrated serum with 1.5% Pure Hyaluronic Acid provides three levels of hydration — surface, mid-layer, and deep. Skin looks visibly plumped and radiant in just one week. Apply 3–4 drops morning and evening before your moisturizer.",
    keyIngredients: ["Hyaluronic Acid (1.5%)", "Micro HA", "Macro HA"],
    skinType: "All skin types, especially dehydrated",
  },
  {
    id: "age-perfect-midnight-cream",
    name: "Age Perfect Cell Renewal Midnight Cream",
    brand: "L'Oréal Paris",
    category: "Skincare",
    emoji: "",
    image: "img/perfect cell renewal.webp",
    tagline: "Overnight renewal for mature skin",
    description:
      "A rich overnight cream with AHA Peeling Complex and Imperial Peony Extract that accelerates the skin's natural renewal process while you sleep. Wake up to visibly smoother, more radiant skin. Ideal for mature skin aged 45+.",
    keyIngredients: [
      "AHA Peeling Complex",
      "Imperial Peony Extract",
      "Vitamin B3",
    ],
    skinType: "Mature skin",
  },
  {
    id: "pure-clay-detox-mask",
    name: "Pure Clay Detox & Brighten Face Mask",
    brand: "L'Oréal Paris",
    category: "Skincare",
    emoji: "",
    image: "img/pure clay face mask.webp",
    tagline: "Deep cleanse with charcoal & 3 pure clays",
    description:
      "A powerful detoxifying mask with Charcoal and 3 Pure Clays that draws out impurities, minimises the look of pores, and leaves skin purified and glowing. Apply a thin layer to dry face, leave for 10–15 minutes, then rinse thoroughly. Use 2–3 times per week.",
    keyIngredients: [
      "Charcoal",
      "Kaolin Clay",
      "Bentonite Clay",
      "Montmorillonite Clay",
    ],
    skinType: "Oily, combination, dull skin",
  },
  {
    id: "bright-reveal-vitamin-c-serum",
    name: "Bright Reveal 12% Pure Vitamin C Serum",
    brand: "L'Oréal Paris",
    category: "Skincare",
    emoji: "",
    image: 'img/bright-reveal-vitamin-c.jpg',
    tagline: "Brighten & reduce dark spots in 1 week",
    description:
      "Powered by 12% Pure Vitamin C, Niacinamide, and Salicylic Acid, this brightening serum visibly reduces dark spots and evens skin tone in as little as one week. Fragrance-free formula. Apply 3–4 drops each morning before your SPF moisturizer.",
    keyIngredients: ["Vitamin C (12%)", "Niacinamide", "Salicylic Acid"],
    skinType: "All skin types, especially uneven/dull",
  },
  {
    id: "hydra-genius-liquid-care",
    name: "Hydra Genius Daily Liquid Care – Normal/Oily",
    brand: "L'Oréal Paris",
    category: "Skincare",
    emoji: "",
    image: "img/genius daily liquid care.webp",
    tagline: "72-hour continuous hydration, oil-free",
    description:
      "A featherlight liquid moisturizer with Hyaluronic Acid and Aloe Vera Water delivering up to 72 hours of continuous hydration without heaviness. Oil-free and non-comedogenic. Perfect as a daily moisturizer for normal-to-oily skin types.",
    keyIngredients: ["Hyaluronic Acid", "Aloe Vera Water"],
    skinType: "Normal to oily",
  },
  // ── MAKEUP ───────────────────────────────────────────────────
  {
    id: "true-match-foundation",
    name: "True Match Super-Blendable Foundation",
    brand: "L'Oréal Paris",
    category: "Makeup",
    emoji: "",
    image: "img/true match foundation.webp",
    tagline: "Perfect colour match for every skin tone",
    description:
      "Available in 45 shades with undertone indicators (W=Warm, N=Neutral, C=Cool), this lightweight foundation provides medium-to-buildable coverage that blends seamlessly. Dermatologist-tested, non-comedogenic with SPF 17. Apply with fingers, brush, or sponge.",
    keyIngredients: ["SPF 17", "Glycerin", "Undertone-matched pigments"],
    skinType: "All skin types",
  },
  {
    id: "infallible-fresh-wear-foundation",
    name: "Infallible 24H Fresh Wear Foundation",
    brand: "L'Oréal Paris",
    category: "Makeup",
    emoji: "",
    image: "img/fresh wear foundation in a powder.webp",
    tagline: "24-hour wear, transfer-proof & breathable",
    description:
      "A full-coverage, transfer-proof foundation that stays flawless for up to 24 hours. Its breathable, water-resistant formula is sweat-proof and won't crack or fade. Available in 30 shades. Ideal for long days or special occasions.",
    keyIngredients: ["Transfer-proof pigments", "Water-resistant film formers"],
    skinType: "All skin types",
  },
  {
    id: "voluminous-original-mascara",
    name: "Voluminous Original Mascara",
    brand: "L'Oréal Paris",
    category: "Makeup",
    emoji: "",
    image: "img/original volumis mascara.jpg",
    tagline: "Up to 5× the volume, clump-free",
    description:
      "The iconic lash mascara with a Soft Bristle Brush that builds up to 5× the volume without clumping. Its conditioning Vitamin formula strengthens lashes while delivering dramatic volume. Available in Black, Blackest Black, and Cobalt Blue.",
    keyIngredients: ["Vitamin B5", "Castor Oil"],
    skinType: "N/A",
  },
  {
    id: "telescopic-mascara",
    name: "Telescopic Original Mascara",
    brand: "L'Oréal Paris",
    category: "Makeup",
    emoji: "",
    image: "img/telescopic.jpg",
    tagline: "Lengthens lashes up to 60% for defined look",
    description:
      "Formulated with a precision Micro-Brush, this lengthening mascara separates each individual lash for dramatic length and definition with zero clumping. Its flexible Vitamin B5 conditioning formula nourishes while it elongates. Washable formula.",
    keyIngredients: ["Vitamin B5", "Micro-Brush technology"],
    skinType: "N/A",
  },
  {
    id: "colour-riche-lipstick",
    name: "Colour Riche Original Satin Lipstick",
    brand: "L'Oréal Paris",
    category: "Makeup",
    emoji: "",
    image: "img/riche original creamy.jpg",
    tagline: "Rich colour, satiny finish, ultra-comfortable",
    description:
      "Over 60 years of iconic lip colour. This satin-finish lipstick delivers rich, vibrant colour in one stroke with a comfortable, non-drying wear. Formulated with Argan Oil and Vitamin E to condition lips while you wear it. Available in 60+ shades.",
    keyIngredients: ["Argan Oil", "Vitamin E", "Satin pigments"],
    skinType: "N/A",
  },
  {
    id: "infallible-lip-kit",
    name: "Infallible Lip 2-Step Longwear Kit",
    brand: "L'Oréal Paris",
    category: "Makeup",
    emoji: "",
    image: "img/infallible matte liquid lipstick.jpg",
    tagline: "16-hour budge-proof lip colour",
    description:
      "A two-step lip kit with a rich colour coat followed by a moisturising top coat. The result is up to 16 hours of transfer-proof lip colour that won't fade or feather. Available in 20 shades from nudes to bold reds.",
    keyIngredients: ["Film-forming polymers", "Moisturising top coat"],
    skinType: "N/A",
  },
  // ── HAIRCARE ─────────────────────────────────────────────────
  {
    id: "elvive-total-repair-shampoo",
    name: "Elvive Total Repair 5 Shampoo",
    brand: "L'Oréal Paris",
    category: "Haircare",
    emoji: "",
    image: "img/total repair 5 repairing.webp",
    tagline: "5 damage repairs in 1 wash",
    description:
      "Targets 5 signs of damaged hair: weakness, roughness, dullness, dryness, and split ends. Formulated with Ceramide and Protein Complex, this repairing shampoo strengthens and nourishes each strand from root to tip. Safe for colour-treated hair.",
    keyIngredients: ["Ceramide", "Protein Complex", "Vitamin B5"],
    skinType: "Damaged, dry, brittle hair",
  },
  {
    id: "elvive-dream-lengths-shampoo",
    name: "Elvive Dream Lengths Shampoo",
    brand: "L'Oréal Paris",
    category: "Haircare",
    emoji: "",
    image: "img/dream lengths shampoo.jpg",
    tagline: "Grow longer, stronger hair",
    description:
      "Enriched with Castor Oil and Vitamins B3 and B5, this shampoo gently cleanses while preventing breakage and strengthening hair from root to tip. Suitable for medium-to-long hair that is prone to breakage. Helps you achieve your length goals faster.",
    keyIngredients: ["Castor Oil", "Vitamin B3", "Vitamin B5"],
    skinType: "Long, breakage-prone hair",
  },
  {
    id: "elvive-colour-protect-shampoo",
    name: "Elvive Colour Protect Shampoo",
    brand: "L'Oréal Paris",
    category: "Haircare",
    emoji: "",
    image: "img/color vibrancy.jpg",
    tagline: "Preserve colour vibrancy for 60 washes",
    description:
      "Specially formulated for colour-treated hair, this shampoo with UV filter and Antioxidants gently cleanses while sealing the hair cuticle to lock in colour and prevent fading. Colour stays vibrant for up to 60 washes.",
    keyIngredients: ["UV Filter", "Antioxidants", "Colour-sealing complex"],
    skinType: "Colour-treated hair",
  },
  {
    id: "elvive-extraordinary-oil",
    name: "Elvive Extraordinary Oil Hair Treatment",
    brand: "L'Oréal Paris",
    category: "Haircare",
    emoji: "",
    image: "img/elvive extraordainry oil.jpg",
    tagline: "Glossy, frizz-free hair with 6 rare oils",
    description:
      "A lightweight, non-greasy oil blend of 6 Rare Flower Oils — Rose, Lotus, Camellia, Marula, Jojoba, and Tiare — providing extraordinary shine, eliminating frizz, and smoothing hair without weighing it down. Apply to damp or dry hair, mid-lengths to ends.",
    keyIngredients: ["Rose Oil", "Lotus Oil", "Camellia Oil", "Marula Oil"],
    skinType: "All hair types, especially frizzy/dull",
  },
  // ── MEN'S ────────────────────────────────────────────────────
  {
    id: "men-expert-hydra-energetic",
    name: "Men Expert Hydra Energetic Face Wash",
    brand: "L'Oréal Paris Men Expert",
    category: "Men's",
    emoji: "",
    image: "img/hydra energentic daily facial cleanser.jpg",
    tagline: "Daily energising cleanser for tired skin",
    description:
      "A powerful yet gentle face wash with Vitamin C and Taurine that thoroughly cleanses, removes excess oil, and instantly energises tired-looking skin. Leaves skin feeling clean, fresh, and healthy. Suitable for daily use morning and evening.",
    keyIngredients: ["Vitamin C", "Taurine"],
    skinType: "Normal to oily men's skin",
  },
  {
    id: "men-expert-vita-lift",
    name: "Men Expert Vita Lift Anti-Wrinkle Moisturiser",
    brand: "L'Oréal Paris Men Expert",
    category: "Men's",
    emoji: "",
    image: "img/Skin care men expert vita.jpg",
    tagline: "Firmer, younger-looking skin for men",
    description:
      "A daily anti-ageing moisturiser with Pro-Retinol and Vitamin C that visibly reduces wrinkles and firms skin in 4 weeks. Lightweight, fast-absorbing formula designed for men's thicker skin. Apply daily after cleansing as the last skincare step.",
    keyIngredients: ["Pro-Retinol", "Vitamin C", "SPF 15"],
    skinType: "All men's skin types",
  },
];
